# Generated by Django 5.1.7 on 2025-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('phone_num', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('BussinesName', models.CharField(max_length=100)),
                ('logoName', models.CharField(max_length=100)),
            ],
        ),
    ]
