# Generated by Django 5.1.7 on 2025-04-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0003_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarterlyRevenue',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
