# Generated by Django 5.1.7 on 2025-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0005_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PhotoFileName',
            field=models.ImageField(upload_to='images/photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logoName',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
