# Generated by Django 5.1.7 on 2025-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0006_alter_profile_photofilename_alter_profile_logoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PhotoFileName',
            field=models.ImageField(default='https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740', upload_to='images/photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logoName',
            field=models.ImageField(default='https://img.freepik.com/premium-vector/person-with-blue-shirt-that-says-name-person_1029948-7040.jpg?semt=ais_hybrid&w=740', upload_to='images/logo/'),
        ),
    ]
