# Generated by Django 5.1.7 on 2025-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0007_alter_profile_photofilename_alter_profile_logoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PhotoFileName',
            field=models.ImageField(upload_to='images/photo/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logoName',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
