# Generated by Django 5.1.7 on 2025-04-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0012_alter_activeclient_user_id_and_more'),
        ('authAPI', '0013_employee_user_id_alter_activeclient_user_id_and_more'),
    ]

    operations = [
    ]
