# Generated by Django 5.1.7 on 2025-04-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0014_merge_20250422_1916'),
        ('authAPI', '0014_merge_20250422_1939'),
    ]

    operations = [
    ]
