# Generated by Django 5.1.7 on 2025-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0015_merge_20250423_1301'),
        ('authAPI', '0015_merge_20250423_1333'),
    ]

    operations = [
    ]
