# Generated by Django 5.1.7 on 2025-04-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0016_merge_20250423_1434'),
        ('authAPI', '0016_merge_20250423_1448'),
    ]

    operations = [
    ]
